version: "3.8"
services:
  app:
    build: .
    container_name: mscliente-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mscliente
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: mscliente-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mscliente
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
